interactive_world_msgs/Placement placement    # the associated placement for the model
float64 decision_value                        # the decision value associated with the model
float64 sigma_x                               # the standard deviation on the X value
float64 sigma_y                               # the standard deviation on the Y value
float64 sigma_z                               # the standard deviation on the Z value
float64 sigma_theta                           # the standard deviation on the theta value
