interactive_world_msgs/Item item                 # item placed in the placement set
interactive_world_msgs/Room room                 # the room the item is placed in
interactive_world_msgs/Surface surface           # the surface the item is placed on
string reference_frame_id                        # name of the target reference frame for the placement set
interactive_world_msgs/Placement[] placements    # the set of placements
