interactive_world_msgs/Item item          # item placed in the placement
interactive_world_msgs/Room room          # the room the item is placed in
interactive_world_msgs/Surface surface    # the surface the item is placed on
string reference_frame_id                 # name of the target reference frame for the placement
geometry_msgs/Point position              # position of the placement
float64 rotation                          # rotation of the placement (along the z-axis)
